### ISSUE TITLE
Guide to upgrading blueprint formats?

### ISSUE THREAD

**Issue by philfreo** [apiaryio/blueprint-parser#8]
Is there a tutorial, guide, or automated tool to assist in upgrading a large .api file(s) using this legacy blueprint format into the new 1A format?

Looking to see if there's anything specific to assisting in format upgrades, rather than just the generic tutorial at https://apiblueprint.org/documentation/tutorial.html

**Comment by kylef** [comment]
Hi @philfreo, we have an automated tool which you can give a go. The tool + specific arguments to convert an Apiary Blueprint to API Blueprint can be found at https://github.com/apiaryio/api-elements.js/tree/master/packages/fury-cli#converting-a-legacy-apiary-blueprint-to-api-blueprint.

However, I am unsure how well the tool currently performs so please check the output. If you need any help converting the document feel free to reach out to me and I am happy to try and help you convert it (kyle.fuller@oracle.com).

**Comment by philfreo** [comment]
Thanks for pointing me to this tool and then fixing the problem. I've confirmed that as of `fury-cli 0.8.11` this tool does seem to handle the conversion. I haven't looked at the file output closely or tried to use it yet, but on quick glance it seems to do the job. Thanks again.
